# Generated by Django 6.0.1 on 2026-01-29 19:35

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrocinio_imagem', models.ImageField(blank=True, upload_to='patrocinio/')),
                ('sedes', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
        migrations.CreateModel(
            name='Subevento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('evento', models.CharField(choices=[('MNR', 'MNR'), ('CBR', 'CBR'), ('OBR', 'OBR'), ('Robotica', 'Robotica'), ('RoboCup Brasil', 'RoboCup Brasil'), ('Todos', 'Todos')], max_length=50)),
                ('icone', models.ImageField(blank=True, upload_to='icones/')),
                ('quadro_avisos', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='TagArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='arquivos/')),
                ('evento', models.CharField(choices=[('MNR', 'MNR'), ('CBR', 'CBR'), ('OBR', 'OBR'), ('Robotica', 'Robotica'), ('RoboCup Brasil', 'RoboCup Brasil'), ('Todos', 'Todos')], max_length=50)),
                ('tags', models.ManyToManyField(to='app.tagarquivo')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('cor', models.CharField(default='#000000', max_length=7)),
                ('action_link', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(to='app.tagdata')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('MNR', 'MNR'), ('CBR', 'CBR'), ('OBR', 'OBR'), ('Robotica', 'Robotica'), ('RoboCup Brasil', 'RoboCup Brasil'), ('Todos', 'Todos')], max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos_funcionarios/')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='app.tagfuncionario')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('evento', models.CharField(choices=[('MNR', 'MNR'), ('CBR', 'CBR'), ('OBR', 'OBR'), ('Robotica', 'Robotica'), ('RoboCup Brasil', 'RoboCup Brasil'), ('Todos', 'Todos')], max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='app.tagnoticia')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('ligas', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
