# Generated by Django 6.0.2 on 2026-02-20 21:19

import app.models
import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da Página (para o Google e Rodapé)')),
                ('patrocinio_vertical', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='A imagem será redimensionada para no máximo 3000x3000 pixels.', keep_meta=True, quality=75, scale=None, size=[3000, 3000], upload_to='patrocinio/', verbose_name='Patrocínio Vertical (Celular) (prop. ideal 9:16)')),
                ('patrocinio_horizontal', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='A imagem será redimensionada para no máximo 3000x3000 pixels.', keep_meta=True, quality=75, scale=None, size=[3000, 3000], upload_to='patrocinio/', verbose_name='Patrocínio Horizontal (Computador) (prop. ideal 16:9)')),
                ('email_contato', models.EmailField(blank=True, max_length=254, verbose_name='Email Principal')),
                ('outros_emails', models.TextField(blank=True, help_text='Separe os e-mails por espaço (ex: contato@exemplo.com suporte@exemplo.com)', verbose_name='Outros Emails de Contato')),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('logo_link_cbr', models.CharField(blank=True, help_text='Link ao clicar na logo no header CBR', verbose_name='Link da Logo (CBR)')),
                ('logo_link_mnr', models.CharField(blank=True, help_text='Link ao clicar na logo no header MNR', verbose_name='Link da Logo (MNR)')),
                ('logo_link_obr', models.CharField(blank=True, help_text='Link ao clicar na logo no header OBR', verbose_name='Link da Logo (OBR)')),
            ],
            options={
                'verbose_name': 'Config. e Patrocínio',
                'verbose_name_plural': 'Config. e Patrocínio',
            },
        ),
        migrations.CreateModel(
            name='PaginaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, unique=True)),
                ('componentes', models.JSONField(blank=True, default=list, verbose_name='🧩 Componentes')),
            ],
            options={
                'verbose_name': 'Página do Estado',
                'verbose_name_plural': 'Páginas dos Estados',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(help_text='Ano (ex: 2026)', max_length=4, unique=True)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('componentes', models.JSONField(blank=True, default=list, verbose_name='🧩 Componentes')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['ano'],
            },
        ),
        migrations.CreateModel(
            name='Subevento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('evento', models.CharField(choices=[('MNR', 'MNR'), ('CBR', 'CBR'), ('OBR', 'OBR'), ('Robotica', 'Robotica'), ('RoboCup Brasil', 'RoboCup Brasil'), ('Todos', 'Todos')], max_length=50)),
                ('icone', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='A imagem será redimensionada para no máximo 3000x3000 pixels.', keep_meta=True, quality=75, scale=None, size=[3000, 3000], upload_to='icones/', verbose_name='Ícone (tam. ideal 256x256)')),
                ('componentes', models.JSONField(blank=True, default=list, verbose_name='🧩 Componentes')),
                ('permalink', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Subevento (Liga)',
                'verbose_name_plural': 'Subeventos (Ligas)',
            },
        ),
        migrations.CreateModel(
            name='TagArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tag de Arquivo',
                'verbose_name_plural': 'Tags de Arquivos',
            },
        ),
        migrations.CreateModel(
            name='TagData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tag de Data',
                'verbose_name_plural': 'Tags de Datas',
            },
        ),
        migrations.CreateModel(
            name='TagFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tag de Funcionário',
                'verbose_name_plural': 'Tags de Funcionários',
            },
        ),
        migrations.CreateModel(
            name='TagNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tag de Notícia',
                'verbose_name_plural': 'Tags de Notícias',
            },
        ),
        migrations.CreateModel(
            name='AtalhoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Texto do link (ex: 'Material de Divulgação')", max_length=100)),
                ('link', models.CharField(help_text='URL externa (https://...) ou caminho interno (ex: /sobre)', max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atalhos', to='app.configuracaoglobal')),
            ],
            options={
                'verbose_name': 'Atalho de Rodapé',
                'verbose_name_plural': 'Atalhos de Rodapé',
            },
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_type', models.CharField(choices=[('RCB', 'Header Padrão RCB'), ('OBR', 'Header OBR'), ('CBR', 'Header CBR'), ('MNR', 'Header MNR')], default='RCB', max_length=50)),
                ('nome', models.CharField(help_text='Texto do link', max_length=100)),
                ('link', models.CharField(help_text='URL externa ou caminho interno', max_length=200)),
                ('escondido', models.BooleanField(default=False, help_text='Se marcado, o link aparece fora do menu "≡" no computador. Para o menu padrão RCB, manter um item escondido fará o mesmo aparecer em todas as páginas.', verbose_name='Escondido no Desktop?')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_menu', to='app.configuracaoglobal')),
            ],
            options={
                'verbose_name': 'Item do Menu',
                'verbose_name_plural': 'Itens do Menu',
            },
        ),
        migrations.CreateModel(
            name='ItemMenuCBR',
            fields=[
            ],
            options={
                'verbose_name': 'Item do Menu CBR',
                'verbose_name_plural': 'Itens do Menu CBR',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.itemmenu',),
        ),
        migrations.CreateModel(
            name='ItemMenuMNR',
            fields=[
            ],
            options={
                'verbose_name': 'Item do Menu MNR',
                'verbose_name_plural': 'Itens do Menu MNR',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.itemmenu',),
        ),
        migrations.CreateModel(
            name='ItemMenuOBR',
            fields=[
            ],
            options={
                'verbose_name': 'Item do Menu OBR',
                'verbose_name_plural': 'Itens do Menu OBR',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.itemmenu',),
        ),
        migrations.CreateModel(
            name='ItemMenuRCB',
            fields=[
            ],
            options={
                'verbose_name': 'Item do Menu RCB',
                'verbose_name_plural': 'Itens do Menu RCB',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.itemmenu',),
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(help_text='Tamanho máximo: 64MB', upload_to='arquivos/', validators=[app.models.validate_file_size], verbose_name='Arquivo (tamanho máximo 64MB)')),
                ('tags', models.ManyToManyField(to='app.tagarquivo')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data', models.DateField()),
                ('cor', models.CharField(default='#000000', max_length=7)),
                ('action_link', models.URLField(blank=True, verbose_name='Link de mais informações')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='app.tagdata')),
            ],
            options={
                'verbose_name': 'Data no Calendário',
                'verbose_name_plural': 'Datas no Calendário',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('instituicao', models.CharField(blank=True, max_length=200, verbose_name='Instituição / Empresa')),
                ('bio', models.TextField(blank=True)),
                ('foto', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='A imagem será redimensionada para no máximo 3000x3000 pixels.', keep_meta=True, quality=75, scale=None, size=[3000, 3000], upload_to='fotos_funcionarios/', verbose_name='Foto (tam. ideal 512x512)')),
                ('tags', models.ManyToManyField(to='app.tagfuncionario')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('chamada', models.CharField(default='Insira uma curta chamada ou introdução para sua notícia aqui...', max_length=200)),
                ('imagem', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='A imagem será redimensionada para no máximo 3000x3000 pixels.', keep_meta=True, quality=75, scale=None, size=[3000, 3000], upload_to='noticias/', verbose_name='Imagem da Notícia (prop. ideal 16:9)')),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('header_type', models.CharField(choices=[('RCB', 'Header Padrão RCB'), ('OBR', 'Header OBR'), ('CBR', 'Header CBR'), ('MNR', 'Header MNR')], default='RCB', help_text='Qual cabeçalho usar nesta notícia (como se fosse uma página)', max_length=50, verbose_name='Cabeçalho da Página')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('permalink', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=255, unique=True)),
                ('tags', models.ManyToManyField(to='app.tagnoticia', verbose_name='Tag(s) da Notícia')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True)),
                ('grupo_extra', models.CharField(blank=True, choices=[('', '—'), ('SUPER', 'Superusuário'), ('SECRETARIA', 'Secretaria'), ('COORD', 'Coordenador de Subevento'), ('REPRESENTANTE', 'Representante Local'), ('MARKETING', 'Marketing')], max_length=20, verbose_name='Grupo de permissão')),
                ('ligas', models.ManyToManyField(blank=True, to='app.subevento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dados Adicionais',
                'verbose_name_plural': 'Dados Extras do Usuário',
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome visível da página (ex: 'Notícias OBR')", max_length=200)),
                ('slug', models.SlugField(blank=True, help_text="Link único, sem espaços (ex: 'material-divulgacao'). Deixe vazio para a página inicial (/)<br><strong>Atenção:</strong> editar este campo pode quebrar links existentes!", max_length=100, verbose_name='Link')),
                ('header_type', models.CharField(choices=[('RCB', 'Header Padrão RCB'), ('OBR', 'Header OBR'), ('CBR', 'Header CBR'), ('MNR', 'Header MNR')], default='RCB', max_length=50, verbose_name='Cabeçalho da Página')),
                ('componentes', models.JSONField(blank=True, default=list, verbose_name='🧩 Componentes')),
                ('evento_associado', models.CharField(blank=True, choices=[('MNR', 'MNR'), ('CBR', 'CBR'), ('OBR', 'OBR'), ('Robotica', 'Robotica'), ('RoboCup Brasil', 'RoboCup Brasil'), ('Todos', 'Todos')], max_length=50, null=True)),
                ('privada', models.BooleanField(default=False, help_text='Se verdadeiro, a página só é visível para quem tiver o link de acesso.', verbose_name='🔒 Página Privada?')),
                ('parent', models.ForeignKey(blank=True, help_text='Página mãe ou de origem (para hierarquia: pagina-de-origem/sua-pagina)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.pagina', verbose_name='Página-mãe')),
            ],
            options={
                'verbose_name': 'Página Dinâmica',
                'verbose_name_plural': 'Páginas Dinâmicas',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'slug'), name='unique_parent_slug'), models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('slug',), name='unique_root_slug')],
            },
        ),
    ]
