# Generated by Django 6.0.1 on 2026-02-21 00:45

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[1200, 1200], upload_to='arquivos/thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='componentes_html',
            field=models.TextField(blank=True, verbose_name='Componentes (HTML cache)'),
        ),
        migrations.AddField(
            model_name='sede',
            name='componentes_html',
            field=models.TextField(blank=True, verbose_name='Componentes (HTML cache)'),
        ),
        migrations.AddField(
            model_name='subevento',
            name='componentes_html',
            field=models.TextField(blank=True, verbose_name='Componentes (HTML cache)'),
        ),
    ]
