# Generated by Django 6.0.1 on 2026-02-26 17:52

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='foto',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Imagem usada no header; será redimensionada para no máximo 3000x3000 pixels.', keep_meta=True, quality=75, scale=None, size=[3000, 3000], upload_to='sedes/', verbose_name='Foto da Sede (prop. ideal 16:9)'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='componentes',
            field=models.JSONField(blank=True, default=list, verbose_name='Conteúdo da Página'),
        ),
        migrations.AlterField(
            model_name='paginaestado',
            name='componentes',
            field=models.JSONField(blank=True, default=list, verbose_name='Conteúdo da Página'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='componentes',
            field=models.JSONField(blank=True, default=list, verbose_name='Conteúdo da Página'),
        ),
        migrations.AlterField(
            model_name='subevento',
            name='componentes',
            field=models.JSONField(blank=True, default=list, verbose_name='Conteúdo da Página'),
        ),
    ]
