# Generated by Django 6.0.2 on 2026-02-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='instituicao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição'),
        ),
    ]
