# Generated by Django 6.0.1 on 2026-07-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Opcional. Deixe em branco para um evento de um único dia.', null=True, verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.DateField(verbose_name='Data de início'),
        ),
    ]
