# Generated by Django 6.0.1 on 2026-02-01 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_grupo_extra_alter_userprofile_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(help_text='Ano (ex: 2026)', max_length=4)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('imagem', models.ImageField(blank=True, upload_to='sedes/')),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'ano'],
            },
        ),
        migrations.AlterModelOptions(
            name='configuracaoglobal',
            options={'verbose_name': 'Dados Configurados', 'verbose_name_plural': 'Dados Configurados'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='header_type',
            field=models.CharField(choices=[('RCB', 'Header Padrão RCB'), ('OBR', 'Header OBR'), ('CBR', 'Header CBR'), ('MNR', 'Header MNR')], default='RCB', help_text='Qual header usar nesta notícia (como se fosse uma página)', max_length=50, verbose_name='Tipo de Header'),
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome visível da página (ex: 'Notícias OBR')", max_length=200)),
                ('slug', models.SlugField(help_text="Link único, min 4 chars, sem espaços (ex: 'noticias-obr')", max_length=100, unique=True)),
                ('header_type', models.CharField(choices=[('RCB', 'Header Padrão RCB'), ('OBR', 'Header OBR'), ('CBR', 'Header CBR'), ('MNR', 'Header MNR')], default='RCB', help_text='Tipo de header para a página', max_length=50)),
                ('componentes', models.JSONField(blank=True, default=list, help_text="Lista ordenada de componentes: [{'type': 'equipe', 'tags': ['obr'], 'title': 'Equipe'}, ...]. A ordem aqui define a exibição.")),
                ('mostrar_no_menu', models.BooleanField(default=False, help_text='Mostrar esta página no menu correspondente ao header_type (apenas páginas de 1º nível)')),
                ('evento_associado', models.CharField(blank=True, choices=[('MNR', 'MNR'), ('CBR', 'CBR'), ('OBR', 'OBR'), ('Robotica', 'Robotica'), ('RoboCup Brasil', 'RoboCup Brasil'), ('Todos', 'Todos')], help_text='Evento ligado (para filtros automáticos)', max_length=50, null=True)),
                ('is_index', models.BooleanField(default=False, editable=False, help_text='Página inicial fixa (slug vazio)')),
                ('parent', models.ForeignKey(blank=True, help_text='Página pai/origem (para hierarquia)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.pagina')),
            ],
            options={
                'verbose_name': 'Página Dinâmica',
                'verbose_name_plural': 'Páginas Dinâmicas',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_index', False)), fields=('slug',), name='unique_slug_non_index')],
            },
        ),
    ]
