# Generated by Django 6.0.1 on 2026-02-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sede_alter_configuracaoglobal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['ano']},
        ),
        migrations.RemoveField(
            model_name='configuracaoglobal',
            name='sedes',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='ordem',
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='patrocinio_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
