# Generated by Django 6.0.1 on 2026-02-22 22:23

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cleanup_components_and_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='tags',
            field=models.ManyToManyField(to='app.tagarquivo', verbose_name='Tag(s) de Arquivo'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, editable=False, force_format=None, keep_meta=True, quality=80, scale=None, size=[1200, 1200], upload_to='arquivos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='data',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Nome / Descrição para a Data'),
        ),
        migrations.AlterField(
            model_name='data',
            name='tags',
            field=models.ManyToManyField(to='app.tagdata', verbose_name='Tag(s) da Data'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tags',
            field=models.ManyToManyField(to='app.tagfuncionario', verbose_name='Tag(s) de Funcionário'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='componentes',
            field=models.JSONField(blank=True, default=list, verbose_name='Configuração da Página'),
        ),
        migrations.AlterField(
            model_name='paginaestado',
            name='componentes',
            field=models.JSONField(blank=True, default=list, verbose_name='Configuração da Página'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='componentes',
            field=models.JSONField(blank=True, default=list, verbose_name='Configuração da Página'),
        ),
        migrations.AlterField(
            model_name='subevento',
            name='componentes',
            field=models.JSONField(blank=True, default=list, verbose_name='Configuração da Página'),
        ),
    ]
