# Generated by Django 6.0.1 on 2026-02-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sede_options_remove_configuracaoglobal_sedes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(blank=True, help_text="Link único, min 4 chars, sem espaços (ex: 'noticias-obr')", max_length=100, unique=True),
        ),
    ]
