# Generated by Django 6.0.1 on 2026-02-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pagina_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pagina',
            name='unique_slug_non_index',
        ),
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(blank=True, help_text="Link único, sem espaços (ex: 'noticias-obr'). Deixe vazio para a página inicial (/)", max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='pagina',
            name='is_index',
        ),
    ]
