# Generated by Django 6.0.1 on 2026-02-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_paginaestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginaestado',
            name='header_type',
        ),
    ]
