# Generated by Django 6.0.1 on 2026-02-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_paginaestado_header_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoglobal',
            options={'verbose_name': 'Configurações e Patrocínio', 'verbose_name_plural': 'Configurações e Patrocínio'},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Data no Calendário', 'verbose_name_plural': 'Datas no Calendário'},
        ),
        migrations.AddField(
            model_name='pagina',
            name='privada',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, adiciona meta robots noindex no head da página.', verbose_name='Privada'),
        ),
    ]
