# Generated by Django 6.0.1 on 2026-02-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_configuracaoglobal_options_alter_data_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoglobal',
            options={'verbose_name': 'Config. e Patrocínio', 'verbose_name_plural': 'Config. e Patrocínio'},
        ),
        migrations.AlterModelOptions(
            name='subevento',
            options={'verbose_name': 'Subevento (Liga)', 'verbose_name_plural': 'Subeventos (Ligas)'},
        ),
        migrations.AlterField(
            model_name='pagina',
            name='privada',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, a página só é visível para quem tiver o link de acesso.', verbose_name='Privada'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grupo_extra',
            field=models.CharField(blank=True, choices=[('', '—'), ('SUPER', 'Superusuário'), ('SECRETARIA', 'Secretaria'), ('COORD', 'Coordenador de Subevento'), ('REPRESENTANTE', 'Representante Local'), ('MARKETING', 'Marketing')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ligas',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ligas',
            field=models.ManyToManyField(blank=True, to='app.subevento'),
        ),
    ]
