# Generated by Django 6.0.1 on 2026-02-03 04:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_convert_ligas_to_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Dados Adicionais', 'verbose_name_plural': 'Dados Extras do Usuário'},
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(help_text='Tamanho máximo: 64MB', upload_to='arquivos/', validators=[app.models.validate_file_size_64mb], verbose_name='Arquivo (tamanho máximo 64MB)'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, help_text='Tamanho máximo: 8MB', upload_to='fotos_funcionarios/', validators=[app.models.validate_file_size_8mb], verbose_name='Foto (tam. ideal 512x512)'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Tamanho máximo: 16MB', upload_to='sedes/', validators=[app.models.validate_file_size_16mb], verbose_name='Imagem (16:9, tam. ideal 1920x1080)'),
        ),
        migrations.AlterField(
            model_name='subevento',
            name='icone',
            field=models.ImageField(blank=True, help_text='Tamanho máximo: 8MB', upload_to='icones/', validators=[app.models.validate_file_size_8mb], verbose_name='Ícone (tam. ideal 256x256)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grupo_extra',
            field=models.CharField(blank=True, choices=[('', '—'), ('SUPER', 'Superusuário'), ('SECRETARIA', 'Secretaria'), ('COORD', 'Coordenador de Subevento'), ('REPRESENTANTE', 'Representante Local'), ('MARKETING', 'Marketing')], max_length=20, verbose_name='Grupo de permissão'),
        ),
    ]
