# Generated by Django 6.0.1 on 2026-02-03 05:07

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userprofile_options_alter_arquivo_arquivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='data',
            name='action_link',
            field=models.URLField(blank=True, verbose_name='Link de mais informações'),
        ),
        migrations.AlterField(
            model_name='data',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='evento',
            field=models.CharField(choices=[('MNR', 'MNR'), ('CBR', 'CBR'), ('OBR', 'OBR'), ('Robotica', 'Robotica'), ('RoboCup Brasil', 'RoboCup Brasil'), ('Todos', 'Todos')], max_length=50, verbose_name='Evento associado'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='header_type',
            field=models.CharField(choices=[('RCB', 'Header Padrão RCB'), ('OBR', 'Header OBR'), ('CBR', 'Header CBR'), ('MNR', 'Header MNR')], default='RCB', help_text='Qual cabeçalho usar nesta notícia (como se fosse uma página)', max_length=50, verbose_name='Cabeçalho da Página'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='tags',
            field=models.ManyToManyField(to='app.tagnoticia', verbose_name='Tag(s) da Notícia'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='header_type',
            field=models.CharField(choices=[('RCB', 'Header Padrão RCB'), ('OBR', 'Header OBR'), ('CBR', 'Header CBR'), ('MNR', 'Header MNR')], default='RCB', help_text='Tipo de cabeçalho para a página', max_length=50, verbose_name='Cabeçalho da Página'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Página mãe ou de origem (para hierarquia: pagina-de-origem/sua-pagina)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.pagina', verbose_name='Página-mãe'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(blank=True, help_text="Link único, sem espaços (ex: 'noticias-obr'). Deixe vazio para a página inicial (/)", max_length=100, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='subevento',
            name='quadro_avisos',
            field=ckeditor.fields.RichTextField(verbose_name='Quadro de Avisos da Liga / Subevento'),
        ),
    ]
