# Generated by Django 6.0.1 on 2026-02-03 21:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_evento_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
        migrations.AlterField(
            model_name='pagina',
            name='componentes',
            field=models.JSONField(blank=True, default=list, verbose_name='🧩 Componentes'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='evento_associado',
            field=models.CharField(blank=True, choices=[('MNR', 'MNR'), ('CBR', 'CBR'), ('OBR', 'OBR'), ('Robotica', 'Robotica'), ('RoboCup Brasil', 'RoboCup Brasil'), ('Todos', 'Todos')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='header_type',
            field=models.CharField(choices=[('RCB', 'Header Padrão RCB'), ('OBR', 'Header OBR'), ('CBR', 'Header CBR'), ('MNR', 'Header MNR')], default='RCB', max_length=50, verbose_name='Cabeçalho da Página'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='mostrar_no_menu',
            field=models.BooleanField(default=False, help_text='Mostrar esta página no menu correspondente ao cabeçalho escolhido', verbose_name='🔍 Mostrar no Menu?'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='privada',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, a página só é visível para quem tiver o link de acesso.', verbose_name='🔒 Página Privada?'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(blank=True, help_text="Link único, sem espaços (ex: 'noticias-obr'). Deixe vazio para a página inicial (/)<br><strong>Atenção:</strong> editar este campo pode quebrar links existentes!", max_length=100, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='paginaestado',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='paginaestado',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Conteúdo da Página'),
        ),
    ]
