# Generated by Django 6.0.1 on 2026-02-13 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_funcionario_user_alter_pagina_componentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoglobal',
            name='outros_emails',
            field=models.TextField(blank=True, help_text='Separe os e-mails por vírgula (ex: contato@exemplo.com, suporte@exemplo.com)', verbose_name='Outros Emails de Contato'),
        ),
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Principal'),
        ),
        migrations.CreateModel(
            name='AtalhoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Texto do link (ex: 'Trabalhe Conosco')", max_length=100)),
                ('link', models.CharField(help_text='URL externa (https://...) ou caminho interno (ex: /sobre)', max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atalhos', to='app.configuracaoglobal')),
            ],
            options={
                'verbose_name': 'Atalho de Rodapé',
                'verbose_name_plural': 'Atalhos de Rodapé',
            },
        ),
    ]
