# Generated by Django 6.0.1 on 2026-02-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_configuracaoglobal_outros_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoglobal',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição da Página (para o Google e Rodapé)'),
        ),
        migrations.AlterField(
            model_name='atalhoglobal',
            name='nome',
            field=models.CharField(help_text="Texto do link (ex: 'Material de Divulgação')", max_length=100),
        ),
    ]
