# Generated by Django 6.0.1 on 2026-02-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_configuracaoglobal_descricao_alter_atalhoglobal_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracaoglobal',
            old_name='patrocinio_imagem',
            new_name='patrocinio_horizontal',
        ),
        migrations.RemoveField(
            model_name='configuracaoglobal',
            name='patrocinio_link',
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='patrocinio_vertical',
            field=models.ImageField(blank=True, upload_to='patrocinio/'),
        ),
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='outros_emails',
            field=models.TextField(blank=True, help_text='Separe os e-mails por espaço (ex: contato@exemplo.com suporte@exemplo.com)', verbose_name='Outros Emails de Contato'),
        ),
    ]
