# Generated by Django 6.0.1 on 2026-02-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_patrocinio_imagem_configuracaoglobal_patrocinio_horizontal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='mostrar_no_menu',
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='logo_link_cbr',
            field=models.URLField(blank=True, help_text='Link ao clicar na logo no header CBR', verbose_name='Link da Logo (CBR)'),
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='logo_link_mnr',
            field=models.URLField(blank=True, help_text='Link ao clicar na logo no header MNR', verbose_name='Link da Logo (MNR)'),
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='logo_link_obr',
            field=models.URLField(blank=True, help_text='Link ao clicar na logo no header OBR', verbose_name='Link da Logo (OBR)'),
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='logo_link_rcb',
            field=models.URLField(blank=True, help_text='Link ao clicar na logo no header RCB', verbose_name='Link da Logo (RCB)'),
        ),
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='patrocinio_horizontal',
            field=models.ImageField(blank=True, upload_to='patrocinio/', verbose_name='Patrocínio Horizontal (Computador)'),
        ),
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='patrocinio_vertical',
            field=models.ImageField(blank=True, upload_to='patrocinio/', verbose_name='Patrocínio Vertical (Celular)'),
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_type', models.CharField(choices=[('RCB', 'Header Padrão RCB'), ('OBR', 'Header OBR'), ('CBR', 'Header CBR'), ('MNR', 'Header MNR')], default='RCB', max_length=50)),
                ('nome', models.CharField(help_text='Texto do link', max_length=100)),
                ('link', models.CharField(help_text='URL externa ou caminho interno', max_length=200)),
                ('grupo', models.CharField(blank=True, help_text='Agrupador para dropdown (opcional). Itens com o mesmo grupo ficarão juntos.', max_length=100)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_menu', to='app.configuracaoglobal')),
            ],
            options={
                'verbose_name': 'Item do Menu',
                'verbose_name_plural': 'Itens do Menu',
            },
        ),
        migrations.CreateModel(
            name='ItemMenuCBR',
            fields=[
            ],
            options={
                'verbose_name': 'Item do Menu CBR',
                'verbose_name_plural': 'Itens do Menu CBR',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.itemmenu',),
        ),
        migrations.CreateModel(
            name='ItemMenuMNR',
            fields=[
            ],
            options={
                'verbose_name': 'Item do Menu MNR',
                'verbose_name_plural': 'Itens do Menu MNR',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.itemmenu',),
        ),
        migrations.CreateModel(
            name='ItemMenuOBR',
            fields=[
            ],
            options={
                'verbose_name': 'Item do Menu OBR',
                'verbose_name_plural': 'Itens do Menu OBR',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.itemmenu',),
        ),
        migrations.CreateModel(
            name='ItemMenuRCB',
            fields=[
            ],
            options={
                'verbose_name': 'Item do Menu RCB',
                'verbose_name_plural': 'Itens do Menu RCB',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.itemmenu',),
        ),
    ]
