# Generated by Django 6.0.1 on 2026-02-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_pagina_mostrar_no_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='logo_link_cbr',
            field=models.CharField(blank=True, help_text='Link ao clicar na logo no header CBR', verbose_name='Link da Logo (CBR)'),
        ),
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='logo_link_mnr',
            field=models.CharField(blank=True, help_text='Link ao clicar na logo no header MNR', verbose_name='Link da Logo (MNR)'),
        ),
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='logo_link_obr',
            field=models.CharField(blank=True, help_text='Link ao clicar na logo no header OBR', verbose_name='Link da Logo (OBR)'),
        ),
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='logo_link_rcb',
            field=models.CharField(blank=True, help_text='Link ao clicar na logo no header RCB', verbose_name='Link da Logo (RCB)'),
        ),
    ]
