# Generated by Django 6.0.1 on 2026-02-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_configuracaoglobal_logo_link_cbr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmenu',
            name='escondido',
            field=models.BooleanField(default=False, help_text='Se marcado, aparece apenas no menu hamburger no Desktop. No mobile, todos aparecem no hamburger.', verbose_name='Escondido no Desktop?'),
        ),
    ]
