# Generated by Django 6.0.1 on 2026-02-15 15:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_itemmenu_escondido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoglobal',
            name='logo_link_rcb',
        ),
        migrations.RemoveField(
            model_name='itemmenu',
            name='grupo',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Tamanho máximo: 8MB', upload_to='noticias/', validators=[app.models.validate_file_size_8mb], verbose_name='Imagem da Notícia (prop. ideal 16:9)'),
        ),
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='patrocinio_horizontal',
            field=models.ImageField(blank=True, help_text='Tamanho máximo: 8MB', upload_to='patrocinio/', validators=[app.models.validate_file_size_8mb], verbose_name='Patrocínio Horizontal (Computador) (prop. ideal 16:9)'),
        ),
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='patrocinio_vertical',
            field=models.ImageField(blank=True, help_text='Tamanho máximo: 8MB', upload_to='patrocinio/', validators=[app.models.validate_file_size_8mb], verbose_name='Patrocínio Vertical (Celular) (prop. ideal 9:16)'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(blank=True, help_text="Link único, sem espaços (ex: 'material-divulgacao'). Deixe vazio para a página inicial (/)<br><strong>Atenção:</strong> editar este campo pode quebrar links existentes!", max_length=100, unique=True, verbose_name='Link'),
        ),
    ]
