# Generated by Django 6.0.1 on 2026-02-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_configuracaoglobal_logo_link_rcb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='chamada',
            field=models.CharField(default='Insira uma curta chamada ou introdução para sua notícia aqui...', max_length=200),
        ),
    ]
