# Generated by Django 6.0.1 on 2026-02-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_noticia_chamada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivo',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['ano'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelOptions(
            name='tagarquivo',
            options={'verbose_name': 'Tag de Arquivo', 'verbose_name_plural': 'Tags de Arquivos'},
        ),
        migrations.AlterModelOptions(
            name='tagdata',
            options={'verbose_name': 'Tag de Data', 'verbose_name_plural': 'Tags de Datas'},
        ),
        migrations.AlterModelOptions(
            name='tagfuncionario',
            options={'verbose_name': 'Tag de Funcionário', 'verbose_name_plural': 'Tags de Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='tagnoticia',
            options={'verbose_name': 'Tag de Notícia', 'verbose_name_plural': 'Tags de Notícias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='permalink',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='escondido',
            field=models.BooleanField(default=False, help_text='Se marcado, o link aparece fora do menu "≡" no computador. Para o menu padrão RCB, manter um item escondido fará o mesmo aparecer em todas as páginas.', verbose_name='Escondido no Desktop?'),
        ),
    ]
